Front end master
WojcikKamil/Rental pull request #1
Opened 2021-02-18 17:19 UTC by Ethalya

2021-02-18 22:09 UTC, kzmijak commented on store/templates/base.html
> +          <a class="nav-link" href="/" >Store</a>
czemu?

2021-02-18 22:11 UTC, Ethalya commented on store/templates/base.html
> +          <a class="nav-link" href="/" >Store</a>
dobre pytanie 🤔

2021-02-18 22:19 UTC, WojcikKamil commented on store/templates/base.html
> +          <a class="nav-link" href="/" >Store</a>
U Pana Doktora Września za takie przewinienie minusowe pkt lecą :C

2021-02-18 22:19 UTC, kzmijak requested changes
Zastanówcie się nad używaniem plików .css żeby przechowywać stylizację w jednym miejscu, to ułatwi późniejszy development

Zamiast label for="" stosujcie alternatywne rozwiązania, np. 
`<label><input type="checkbox">Some text</label>`

2021-02-18 22:19 UTC, kzmijak commented on store/templates/cart.html
> +            col-lg-3 float-right" style="margin-left: 35%; margin-right: 35%; background-color: #00d1b2; color: white; font-weight: bold;">Checkout</a>
Używanie style w templatce samo w sobie jest niepożądane, a wprowadzanie więcej niż dwóch reguł jest złą praktyką

2021-02-18 22:19 UTC, kzmijak commented on store/templates/login.html
> +                <label for="" style="margin-left: 44%">Email</label>
for="" ??

2021-02-18 22:19 UTC, kzmijak commented on store/templates/index.html
> +  <p style="color: white; font-size: 16px; font-family: Arial; text-align: center; padding: 25px"> 2021 © Developed by : Maria Urban, Rafał Czytajło, Kacper Żmijak, Kamil Wójcik<br></p>
Za długi dekorator, używajcie plików .css

2021-02-18 22:22 UTC, WojcikKamil commented on store/templates/cart.html
> +            col-lg-3 float-right" style="margin-left: 35%; margin-right: 35%; background-color: #00d1b2; color: white; font-weight: bold;">Checkout</a>
To akurat mój grzech :C ale jutro to poprawię, bo to miało być do pop-upa, aby region i country wybierać. To samo folder "orders" w templatce jest do wywalenia

2021-02-18 22:23 UTC, kzmijak commented
Nazwa brancha w żaden sposób nie opisuje jego przeznaczenia, na przyszłość róbcie tak by potem wiedzieć co było robione z listy historii,- bez potrzeby czytania szczegółów

To samo tyczy się opisów commitów

2021-02-18 22:23 UTC, Ethalya commented on store/templates/cart.html
> +            col-lg-3 float-right" style="margin-left: 35%; margin-right: 35%; background-color: #00d1b2; color: white; font-weight: bold;">Checkout</a>
nie musisz wszystkiego komentować, miałam małą spine z plikiem css

2021-02-18 22:24 UTC, WojcikKamil commented on store/templates/index.html
> +  <p style="color: white; font-size: 16px; font-family: Arial; text-align: center; padding: 25px"> 2021 © Developed by : Maria Urban, Rafał Czytajło, Kacper Żmijak, Kamil Wójcik<br></p>
Dyrektorze, jutro zostanie zrobiony globalny css!

2021-02-18 22:26 UTC, kzmijak commented on store/templates/index.html
> +  <p style="color: white; font-size: 16px; font-family: Arial; text-align: center; padding: 25px"> 2021 © Developed by : Maria Urban, Rafał Czytajło, Kacper Żmijak, Kamil Wójcik<br></p>
już go macie w Rental/store/templates/style.css
Ale używajcie go tylko gdy faktycznie są to klasy używane w więcej niż kilku plikach, a nie do przechowywania wszystkich klas

2021-02-18 22:28 UTC, kzmijak commented on store/templates/cart.html
> +            col-lg-3 float-right" style="margin-left: 35%; margin-right: 35%; background-color: #00d1b2; color: white; font-weight: bold;">Checkout</a>
dzwoń na policję bo zostaję na parkiecie

2021-02-18 22:29 UTC, Ethalya commented on store/templates/cart.html
> +            col-lg-3 float-right" style="margin-left: 35%; margin-right: 35%; background-color: #00d1b2; color: white; font-weight: bold;">Checkout</a>
jak Cię Kacperek spotkam..... :>

2021-02-18 22:29 UTC, WojcikKamil commented on store/templates/cart.html
> +            col-lg-3 float-right" style="margin-left: 35%; margin-right: 35%; background-color: #00d1b2; color: white; font-weight: bold;">Checkout</a>
XDDDDDDDD pomoge!

2021-02-21 12:02 UTC, kzmijak commented on store/static/css/base.css
> +#navbarSupportedContent {
tak na przyszłość nie używajcie camelCase w CSSach, tylko rozdzielajcie wyrazy myślnikami - navbar-support-content
[Artykuł](https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/)

2021-02-21 12:06 UTC, kzmijak commented
Zrobiliście olbrzymiego Pull Requesta, teraz spróbujcie sobie przejrzeć wszystkie zmiany i wyciągnijcie wnioski - każda mała funkcjonalność powinna mieć oddzielnego taska i brancha, tutaj połączyliście pół galaktyki w jedną całość - przepchnę to ale w sumie tylko dlatego że nie chcę mi się tego wszystkiego sprawdzać

2021-02-21 12:48 UTC, merged

2021-02-21 16:11 UTC, Ethalya commented on store/static/css/base.css
> +#navbarSupportedContent {
to było jedyne "id", które było już w htmlu, przez co już wszystkie w ten sposób pozmieniałam D: mogłam przeczytać - my bad